version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-161-58-21.compute-1.amazonaws.com
            database: d82mg79uhhgblp
            schema: public
            user: cvdqsylsbailzc
            password: 75247ff9a98bf044be98c72f744326a386b2c5d2cde6fe50cca866029b4353e0
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
